// AUTO-GENERATED by nwn-manager repack — regenerated each build, do not edit.
// Opt in from any module event: ExecuteScript("nwnmgr_bstamp", oPC);
void main() { SendMessageToPC(OBJECT_SELF, "Module last edited: 2026-06-10 23:38 CDT (git e17ee6dd996-dirty)"); }
